name: Update Current Time

on:
  schedule:
    - cron: '*/10 * * * *'  
  workflow_dispatch:  

jobs:
  update_time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current time
        run: |
          CURRENT_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")
          CURRENT_S=$(date -u +"%S")
          
          mkdir -p "x"
          echo "$CURRENT_TIME" >> "x/0_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/1_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/2_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/3_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/4_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/5_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/6_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/7_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/8_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/9_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/10_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/11_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/12_$CURRENT_S"
          echo "$CURRENT_TIME" >> "x/13_$CURRENT_S"
          

      - name: Commit updated time
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add time.txt
          git commit -m "Update time to $CURRENT_TIME"
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
